Cache the last downloaded update and reuse if requested again
huntresslabs/win-service-updater pull request #14
Opened 2022-07-29 02:33 UTC by tramzee

This change keeps a copy of the last downloaded update file (wyu) and
will reuse that file if the checksum matches the checksum specified in
the update wys file.

[SC-46784]

2022-07-29 02:37 UTC, tramzee commented on updater/handler.go
> -
The adler32 check got moved to `getWyuFile`

2022-07-29 15:17 UTC, hunting-for-robert-r-meyer commented on updater/wys.go
> +// copyFile is a utility function to copy one file to another
Is there another place this should live? Utils? FileUtils? Magic File Handling?

2022-07-29 17:26 UTC, jamesodoherty-huntress commented on updater/wys.go
> +// copyFile is a utility function to copy one file to another
I think it's small enough to keep it local until there's a proven need to reuse it. It's a standalone function purely for clarity at the call site.

2022-08-01 13:33 UTC, jamesodoherty-huntress requested changes
I think some of the code must have gotten transposed. It looks like it's not passing the unit tests because of a reversed if/else.

2022-08-01 13:33 UTC, jamesodoherty-huntress commented on updater/wys.go
> +	lastWyuDownload := wys.lastWyuDownload()
This method never calls copyFile if UpdateFileAdler32 is 0, so we should just guard against that condition here at the top and return a useful error message rather than looking like we succeed but not creating the destination file at `fp`.

2022-08-01 13:33 UTC, jamesodoherty-huntress commented on updater/wys.go
> +		if VerifyAdler32Checksum(wys.UpdateFileAdler32, fp) {
This should be `if !VerifyAdler32Checksum(...`

The existing unit test looks like it should catch this.

2022-08-08 21:02 UTC, hunting-for-robert-r-meyer commented on updater/wys.go
> +		if VerifyAdler32Checksum(wys.UpdateFileAdler32, fp) {
@jamesodoherty-huntress we good on this change?

2022-08-09 13:58 UTC, tramzee commented on updater/wys.go
> +	lastWyuDownload := wys.lastWyuDownload()
I have made this fix under the assumption that we are not relying on the fact that an empty Adler32 in the the WYS file is an implicit match.

2022-08-09 17:12 UTC, jamesodoherty-huntress approved these changes
Looks good! We should really look into adding some GitHub actions to this repo to run the build/lint since it's public and open source.

2022-08-11 13:12 UTC, brandonlamhuntress approved these changes

2022-08-11 19:02 UTC, merged